### ISSUE TITLE
1.02 版本 \> 打开失败

### ISSUE THREAD

**Issue by motanzg** [mowtwo/utools-file-browser#2]
你好，插件版本1.02，utools 版本5.1.1，winodws10系统，执行 \ > 没有打开cmd.exe，有屏幕闪一下的样子， 执行 \ ? 选择开源地址倒是打开了 cmd.exe。重启卸载插件都不能解决。

**Comment by mowtwo** [comment]
可能是版本差异，我昨天修复了一些问题，修改了启动的逻辑，插件商城版本不一样，你现在应用商城版本号可以发一下吗

**Comment by mowtwo** [comment]
好的，我后面测试一下看看

**Comment by mowtwo** [comment]
我测试了一下，好像没有复现这个问题，你可以把Windows系统的具体版本发一下，我目前是在内核Windows10 19041.264上

**Comment by mowtwo** [comment]
或者发一下你执行的命令是什么，有可能是执行失败了，或者被安全卫士之类的拦截了

**Comment by motanzg** [comment]
![111](https://github.com/mowtwo/utools-file-browser/assets/29702075/70141e92-5d1d-45d9-b01d-81e18aa01755)
windows10 19045.4412，只安装了火绒，\ >插件1.02的上一个版本没有问题的。

**Comment by mowtwo** [comment]
理解了，目前会出现这个bug的因为应该就是你直接执行了空指令的原因，因为在1.0.3中修复了跨盘符执行指令无法正确切换盘符的问题，这里面修改了一些写法，其实现在这个情况才是正确的情况，之前其实是错误执行了指令依然打开了cmd。不过我会在下个版本中加入判断，如果空指令改成在当前路径下默认启动一个cmd

**Comment by mowtwo** [comment]
1.0.4中已解决
